image: golang:1.25.5

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  REGISTRY: registry.detmir.ru
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  OUTPUT_NAME: __bin__/$CI_PROJECT_NAME

stages:
  - lint
  - test
  - build

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  extends: .go-cache
  allow_failure: false
  script:
    - golangci-lint run -v

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - mkdir -p coverage
    - go test -race $(go list ./... | grep -v /vendor/) -coverprofile=coverage/coverage.out -covermode atomic
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage/coverage.out > coverage/cobertura.xml
    - go tool cover -func coverage/coverage.out
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
  allow_failure: false
  timeout: 5 min

build:
  stage: build
  script:
    - . ./scripts/build-pgm.sh
